// Do not edit - generated by Style Dictionary (Canopy Roots, @rogueoak/roots).
// Brand: thoughtstream. Regenerate with: npx roots-swift <brand.config.json>
//
// Vendored from canopy (packages/roots, brand thoughtstream). Do not edit here.
// Re-sync after upstream changes, from the canopy roots package, with:
//   npx roots-swift examples/thoughtstream/brand.config.json
// then copy dist/thoughtstream/Tokens.swift over this file.
//
// Colors: each semantic role resolves to a light + dark hex and adapts to the color scheme.
// Dimensions: rem is converted to points at 16pt/rem (1rem = 16px = 16pt); a raw px value
// (radius.full) is emitted as-is. Spacing/radius/type sizes come from Canopy core tokens,
// not the brand.

#if canImport(UIKit)
import UIKit
#endif
import SwiftUI

public extension Color {
    /// A color that resolves to `light` in light mode and `dark` in dark mode.
    /// Hexes are 0xRRGGBB. On platforms with UIKit this uses a dynamic UIColor provider so it
    /// updates live when the color scheme changes; elsewhere it falls back to the light value.
    init(light: UInt, dark: UInt) {
        // watchOS has no `UIColor(dynamicProvider:)` / trait `userInterfaceStyle` (spec 0023): the watch
        // renders on a dark background, so it resolves to the DARK value. iOS keeps the live dynamic
        // provider. This platform guard is the one hand-edit to this generated file; preserve it on a
        // re-sync from Canopy.
        #if os(watchOS)
        self = Color(rgb: dark)
        #elseif canImport(UIKit)
        self = Color(UIColor { traits in
            traits.userInterfaceStyle == .dark ? UIColor(rgb: dark) : UIColor(rgb: light)
        })
        #else
        self = Color(rgb: light)
        #endif
    }

    init(rgb: UInt) {
        self.init(
            .sRGB,
            red: Double((rgb >> 16) & 0xFF) / 255.0,
            green: Double((rgb >> 8) & 0xFF) / 255.0,
            blue: Double(rgb & 0xFF) / 255.0,
            opacity: 1.0
        )
    }
}

#if canImport(UIKit)
private extension UIColor {
    convenience init(rgb: UInt) {
        self.init(
            red: CGFloat((rgb >> 16) & 0xFF) / 255.0,
            green: CGFloat((rgb >> 8) & 0xFF) / 255.0,
            blue: CGFloat(rgb & 0xFF) / 255.0,
            alpha: 1.0
        )
    }
}
#endif

/// Canopy semantic colors. Each adapts to the current color scheme.
public enum CanopyColor {
    public static let accent = Color(light: 0x33A89F, dark: 0x5CC2B9)
    public static let accentForeground = Color(light: 0x082322, dark: 0x082322)
    public static let accentHover = Color(light: 0x5CC2B9, dark: 0x93D9D2)
    public static let accentStrong = Color(light: 0x195F5A, dark: 0x5CC2B9)
    public static let bg = Color(light: 0xF3F6F6, dark: 0x0E1618)
    public static let border = Color(light: 0xCBD9DA, dark: 0x3A4E51)
    public static let borderStrong = Color(light: 0xA7BDBF, dark: 0x476063)
    public static let danger = Color(light: 0x87392C, dark: 0xC87C6D)
    public static let dangerActive = Color(light: 0x55251D, dark: 0xECCDC7)
    public static let dangerForeground = Color(light: 0xF6E8E5, dark: 0x26100C)
    public static let dangerHover = Color(light: 0x6C2E24, dark: 0xDBA49A)
    public static let disabled = Color(light: 0xE6EDED, dark: 0x2C3D40)
    public static let disabledForeground = Color(light: 0x7C989B, dark: 0x476063)
    public static let info = Color(light: 0x32575F, dark: 0x6BA1AA)
    public static let infoForeground = Color(light: 0xE4EDEF, dark: 0x0F1B1E)
    public static let muted = Color(light: 0xE6EDED, dark: 0x1E3238)
    public static let mutedForeground = Color(light: 0x476063, dark: 0xA7BDBF)
    public static let mutedRaised = Color(light: 0xE6EDED, dark: 0x3A4E51)
    public static let overlay = Color(light: 0x1E3238, dark: 0x0E1618)
    public static let primary = Color(light: 0x42666F, dark: 0x8FB6BB)
    public static let primaryActive = Color(light: 0x2F4448, dark: 0x63959C)
    public static let primaryForeground = Color(light: 0xEEF4F5, dark: 0x141F22)
    public static let primaryHover = Color(light: 0x375258, dark: 0xB8D2D5)
    public static let ring = Color(light: 0x42666F, dark: 0x8FB6BB)
    public static let ringOffset = Color(light: 0xFFFFFF, dark: 0x0E1618)
    public static let secondary = Color(light: 0x356C73, dark: 0x72B6B8)
    public static let secondaryActive = Color(light: 0x294749, dark: 0xD0E8E8)
    public static let secondaryForeground = Color(light: 0xE9F4F4, dark: 0x122123)
    public static let secondaryHover = Color(light: 0x2E585D, dark: 0xA5D2D3)
    public static let success = Color(light: 0x367049, dark: 0x549B73)
    public static let successForeground = Color(light: 0xE8F2EC, dark: 0x102015)
    public static let surface = Color(light: 0xFBFDFD, dark: 0x18262A)
    public static let surfaceRaised = Color(light: 0xFFFFFF, dark: 0x2C3D40)
    public static let text = Color(light: 0x1E3238, dark: 0xE6EDED)
    public static let textInverted = Color(light: 0xF3F6F6, dark: 0x1E3238)
    public static let textMuted = Color(light: 0x476063, dark: 0xA7BDBF)
    public static let textSubtle = Color(light: 0x5C797C, dark: 0x7C989B)
    public static let warning = Color(light: 0x78621B, dark: 0xB09030)
    public static let warningForeground = Color(light: 0xF5EFD9, dark: 0x211B08)
}

/// Canopy spacing scale, in points (rem * 16).
public enum CanopySpacing {
    public static let x0: CGFloat = 0
    public static let x0_5: CGFloat = 2
    public static let x1: CGFloat = 4
    public static let x1_5: CGFloat = 6
    public static let x2: CGFloat = 8
    public static let x3: CGFloat = 12
    public static let x4: CGFloat = 16
    public static let x5: CGFloat = 20
    public static let x6: CGFloat = 24
    public static let x8: CGFloat = 32
    public static let x10: CGFloat = 40
    public static let x12: CGFloat = 48
    public static let x16: CGFloat = 64
    public static let x20: CGFloat = 80
    public static let x24: CGFloat = 96
    public static let x32: CGFloat = 128
}

/// Canopy corner radii, in points.
public enum CanopyRadius {
    public static let x2xl: CGFloat = 24
    public static let full: CGFloat = 9999
    public static let lg: CGFloat = 12
    public static let md: CGFloat = 8
    public static let none: CGFloat = 0
    public static let sm: CGFloat = 4
    public static let xl: CGFloat = 16
}

/// Canopy type scale: sizes in points, matching line-height multipliers, and Font helpers.
public enum CanopyFont {
    public static let sizeXs: CGFloat = 12
    public static let sizeSm: CGFloat = 14
    public static let sizeBase: CGFloat = 16
    public static let sizeLg: CGFloat = 18
    public static let sizeXl: CGFloat = 20
    public static let sizeX2xl: CGFloat = 24
    public static let sizeX3xl: CGFloat = 30
    public static let sizeX4xl: CGFloat = 36
    public static let sizeX5xl: CGFloat = 48
    public static let sizeX6xl: CGFloat = 60

    public static let leadingNone: CGFloat = 1
    public static let leadingNormal: CGFloat = 1.55
    public static let leadingRelaxed: CGFloat = 1.75
    public static let leadingSnug: CGFloat = 1.35
    public static let leadingTight: CGFloat = 1.2

    public static func sizeXsFont() -> Font { .system(size: sizeXs) }
    public static func sizeSmFont() -> Font { .system(size: sizeSm) }
    public static func sizeBaseFont() -> Font { .system(size: sizeBase) }
    public static func sizeLgFont() -> Font { .system(size: sizeLg) }
    public static func sizeXlFont() -> Font { .system(size: sizeXl) }
    public static func sizeX2xlFont() -> Font { .system(size: sizeX2xl) }
    public static func sizeX3xlFont() -> Font { .system(size: sizeX3xl) }
    public static func sizeX4xlFont() -> Font { .system(size: sizeX4xl) }
    public static func sizeX5xlFont() -> Font { .system(size: sizeX5xl) }
    public static func sizeX6xlFont() -> Font { .system(size: sizeX6xl) }
}
